name: 'medical_data_quality_pipeline'
version: '1.0.0'
config-version: 2

profile: 'medical_data_quality_pipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  medical_data_quality_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table